version: 2.1

executors:
  xcode-10_3:
    macos:
      xcode: 10.3.0

commands:
  install:
    parameters:
      head:
        type: boolean
    steps:
    - run:
        name: Brown magic to prevent a Python2 zombie from resurfacing
        command: |
          brew uninstall python@2
    - run:
        # FFS, idiotic developers doing dumb things. This whole thing is like
        # Bitcoin, a slowly burning dumpster fire that just DOESN'T SCALE.
        name: More brown magic to make Homebrew updateable
        command: |
          git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
          git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
    - run:
        name: Update Homebrew
        command: |
          brew update
          brew --version
    - when:
        condition:
          # What kind of INSANE language is this?!
          equal: [ master, << pipeline.git.branch >> ]
        steps:
        - run:
            name: Tap the repository
            command: |
              brew tap mosra/magnum
    - unless:
        condition:
          equal: [ master, << pipeline.git.branch >> ]
        steps:
        - checkout:
            path: /usr/local/Homebrew/Library/Taps/mosra/homebrew-magnum
    - run:
        name: Install everything
        command: |
          brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/corrade
          brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum
          brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-plugins
          brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-extras
          brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-integration
          brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-bindings
          brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-examples
    - checkout

  verify-imageconverter:
    steps:
    - run:
        name: Verify magnum-imageconverter
        command: |
          magnum-imageconverter package/ci/file.jpg file.png
          file file.png

  verify-sceneconverter:
    steps:
    - run:
        name: Verify magnum-sceneconverter
        command: |
          magnum-sceneconverter package/ci/cube.obj cube.ply
          file cube.ply

  verify-shaderconverter:
    steps:
    - run:
        name: Verify magnum-shaderconverter
        command: |
          magnum-shaderconverter package/ci/triangle-shaders.spv triangle-shaders.spvasm
          file triangle-shaders.spvasm

  verify-bindings:
    steps:
    - run:
        name: Verify Python bindings
        command: |
          python3 -c "from magnum import *; print(Matrix3.rotation(Deg(25.0)))"

jobs:
  stable:
    # Using 9.4 would be great to ensure compatibility, however spirv-tools
    # isn't on the stale Homebrew on any earlier image than 10.3.
    executor: xcode-10_3
    steps:
    - install:
        head: false
    - verify-imageconverter
    # TODO: enable these when next release is out
    #- verify-sceneconverter
    #- verify-shaderconverter
    - verify-bindings

  head:
    # Using 9.4 would be great to ensure compatibility, however spirv-tools
    # isn't on the stale Homebrew on any earlier image than 10.3.
    executor: xcode-10_3
    steps:
    - install:
        head: true
    - verify-imageconverter
    - verify-sceneconverter
    - verify-shaderconverter
    - verify-bindings

workflows:
  version: 2
  build:
    jobs:
    - stable
    - head
