version: 2.1

executors:
  # On 14.3.1 it attempts to build Python from scratch because "such old
  # version is not supported", FFS. January 2026. 15.4 is the oldest that is
  # available on the default M4 resource class.
  xcode-15_4:
    macos:
      xcode: 15.4.0

commands:
  install:
    parameters:
      head:
        type: boolean
    steps:
    - run:
        name: Undo whatever cursed crap is making Homebrew fail now
        # As of August 2025, without this the brew update below fails with
        # fatal: could not read Username for 'https://github.com': terminal prompts disabled
        # Error: homebrew/homebrew-cask-versions does not exist! Run `brew untap homebrew/homebrew-cask-versions` to remove it.
        # The uninstall is needed because otherwise it refuses to remove the
        # tap. FFS.
        command: |
          brew uninstall temurin17
          brew untap homebrew/homebrew-cask-versions
    - run:
        name: Update Homebrew
        command: |
          brew update
          brew --version
    - run:
        name: Uninstall the pyenv crap and install plain python instead
        # Otherwise magnum bindings installed by homebrew are unreachable by
        # actual user-side python. THIS ALL USED TO WORK BUT NOT ANYMORE. They
        # subsequently added `brew pyenv-sync` in an attempt to fix this trash
        # fire, but that damn thing doesn't work at all either. Fuck it, then.
        # https://github.com/orgs/Homebrew/discussions/4664
        # https://github.com/Homebrew/brew/issues/17563
        command: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew remove pyenv
          HOMEBREW_NO_AUTO_UPDATE=1 brew install python
          rm -r ~/.pyenv
    - when:
        condition:
          # What kind of INSANE language is this?!
          equal: [ master, << pipeline.git.branch >> ]
        steps:
        - run:
            name: Tap the repository
            command: |
              brew tap mosra/magnum
    - unless:
        condition:
          equal: [ master, << pipeline.git.branch >> ]
        steps:
        - checkout:
            path: /opt/homebrew/Library/Taps/mosra/homebrew-magnum
        - run:
            name: Take Homebrew out for a piss once again and then restore the proper tap branch
            # Used to be --preinstall, now it's --auto-update. FUCK YOU for not
            # properly documenting any of this and for breaking stuff every 6
            # months. https://github.com/orgs/Homebrew/discussions/5896
            command: |
              brew update --auto-update
              cd /opt/homebrew/Library/Taps/mosra/homebrew-magnum
              git checkout << pipeline.git.branch >>
    - run:
        name: Install everything
        # To be EXTRA SURE it doesn't change the tap under my fingers again,
        # disallow it from updating anything
        command: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/corrade
          HOMEBREW_NO_AUTO_UPDATE=1 brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum
          HOMEBREW_NO_AUTO_UPDATE=1 brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-plugins
          HOMEBREW_NO_AUTO_UPDATE=1 brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-extras
          HOMEBREW_NO_AUTO_UPDATE=1 brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-integration
          HOMEBREW_NO_AUTO_UPDATE=1 brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-bindings
          HOMEBREW_NO_AUTO_UPDATE=1 brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-examples
    - unless:
        condition:
          equal: [ master, << pipeline.git.branch >> ]
        steps:
        - run:
            name: Once again check that Homebrew didn't replace the tap with something else
            command: |
              cd /opt/homebrew/Library/Taps/mosra/homebrew-magnum
              [[ $(git rev-parse --abbrev-ref HEAD) == "<< pipeline.git.branch >>" ]]
    - checkout

  verify-version-headers:
    steps:
    - run:
        name: Verify generated version.h files
        command: |
          grep "#define CORRADE_VERSION_COMMIT" /opt/homebrew/include/Corrade/version.h
          grep "#define MAGNUM_VERSION_COMMIT" /opt/homebrew/include/Magnum/version.h
          grep "#define MAGNUMPLUGINS_VERSION_COMMIT" /opt/homebrew/include/Magnum/versionPlugins.h
          grep "#define MAGNUMEXTRAS_VERSION_COMMIT" /opt/homebrew/include/Magnum/versionExtras.h
          grep "#define MAGNUMINTEGRATION_VERSION_COMMIT" /opt/homebrew/include/Magnum/versionIntegration.h
          grep "#define MAGNUMBINDINGS_VERSION_COMMIT" /opt/homebrew/include/Magnum/versionBindings.h

  verify-imageconverter:
    steps:
    - run:
        name: Verify magnum-imageconverter
        command: |
          magnum-imageconverter package/ci/file.jpg file.png
          file file.png

  verify-sceneconverter:
    steps:
    - run:
        name: Verify magnum-sceneconverter
        command: |
          magnum-sceneconverter package/ci/cube.obj cube.ply
          file cube.ply

  verify-shaderconverter:
    steps:
    - run:
        name: Verify magnum-shaderconverter
        command: |
          magnum-shaderconverter package/ci/triangle-shaders.spv triangle-shaders.spvasm
          file triangle-shaders.spvasm

  verify-bindings:
    steps:
    - run:
        name: Verify Python bindings
        command: |
          python3 -c "from magnum import *; print(Matrix3.rotation(Deg(25.0)))"

jobs:
  stable:
    executor: xcode-15_4
    steps:
    - install:
        head: false
    - verify-version-headers
    - verify-imageconverter
    - verify-sceneconverter
    - verify-shaderconverter
    - verify-bindings

  head:
    executor: xcode-15_4
    steps:
    - install:
        head: true
    - verify-imageconverter
    - verify-sceneconverter
    - verify-shaderconverter
    - verify-bindings

workflows:
  version: 2
  build:
    jobs:
    - stable
    - head
