version: 2.1

executors:
  # Used 10.3 before, but it started building CMake from sources. That's crap,
  # so use something newer instead.
  xcode-11_5:
    macos:
      xcode: 11.5

commands:
  install:
    parameters:
      head:
        type: boolean
    steps:
    - run:
        name: Update Homebrew
        command: |
          brew update
          brew --version
    - when:
        condition:
          # What kind of INSANE language is this?!
          equal: [ master, << pipeline.git.branch >> ]
        steps:
        - run:
            name: Tap the repository
            command: |
              brew tap mosra/magnum
    - unless:
        condition:
          equal: [ master, << pipeline.git.branch >> ]
        steps:
        - checkout:
            path: /usr/local/Homebrew/Library/Taps/mosra/homebrew-magnum
        - run:
            name: Take Homebrew out for a piss once again and then restore the proper tap branch
            command: |
              brew update --preinstall
              cd /usr/local/Homebrew/Library/Taps/mosra/homebrew-magnum
              git checkout << pipeline.git.branch >>
    - run:
        name: Install everything
        # To be EXTRA SURE it doesn't change the tap under my fingers again,
        # disallow it from updating anything
        command: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/corrade
          HOMEBREW_NO_AUTO_UPDATE=1 brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum
          HOMEBREW_NO_AUTO_UPDATE=1 brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-plugins
          HOMEBREW_NO_AUTO_UPDATE=1 brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-extras
          HOMEBREW_NO_AUTO_UPDATE=1 brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-integration
          HOMEBREW_NO_AUTO_UPDATE=1 brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-bindings
          HOMEBREW_NO_AUTO_UPDATE=1 brew install <<# parameters.head >> --HEAD <</ parameters.head >> mosra/magnum/magnum-examples
    - unless:
        condition:
          equal: [ master, << pipeline.git.branch >> ]
        steps:
        - run:
            name: Once again check that Homebrew didn't replace the tap with something else
            command: |
              cd /usr/local/Homebrew/Library/Taps/mosra/homebrew-magnum
              [[ $(git rev-parse --abbrev-ref HEAD) == "<< pipeline.git.branch >>" ]]
    - checkout

  verify-imageconverter:
    steps:
    - run:
        name: Verify magnum-imageconverter
        command: |
          magnum-imageconverter package/ci/file.jpg file.png
          file file.png

  verify-sceneconverter:
    steps:
    - run:
        name: Verify magnum-sceneconverter
        command: |
          magnum-sceneconverter package/ci/cube.obj cube.ply
          file cube.ply

  verify-shaderconverter:
    steps:
    - run:
        name: Verify magnum-shaderconverter
        command: |
          magnum-shaderconverter package/ci/triangle-shaders.spv triangle-shaders.spvasm
          file triangle-shaders.spvasm

  verify-bindings:
    steps:
    - run:
        name: Verify Python bindings
        command: |
          python3 -c "from magnum import *; print(Matrix3.rotation(Deg(25.0)))"

jobs:
  stable:
    executor: xcode-11_5
    steps:
    - install:
        head: false
    - verify-imageconverter
    - verify-sceneconverter
    # TODO: enable this when next release is out
    #- verify-shaderconverter
    - verify-bindings

  head:
    executor: xcode-11_5
    steps:
    - install:
        head: true
    - verify-imageconverter
    - verify-sceneconverter
    - verify-shaderconverter
    - verify-bindings

workflows:
  version: 2
  build:
    jobs:
    - stable
    - head
